name: flutter_hyotalk_app
description: "hyotalk 2.0"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.2.3
  go_router: ^13.0.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - .env.dev
    - .env.stage
    - .env.prod
    - pubspec.yaml
    - assets/images/
    - assets/icons/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Thin.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Light.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Black.otf
